const TestimonialAPi = [
  {
    id: 1,
    image: "../../img/t1.jpg",
    design: "NCD - DEsign",
    name: "Mevine Thoda",
    officer: "Marketing Officer",
    post: "CEo - marketing",
    date: "THoda Department - Mar  4 , 2018 - Aug 30 ,2021",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi repudiandae quod ducimus voluptas atque unde vitae ut consequuntur delectus, perferendis quisquam ab cum dignissimos numquam beatae iste ad, distinctio amet!",
  },
  {
    id: 2,
    image: "../../img/t2.jpg",
    design: "NCD - DEsign",
    name: "Mevine Thoda",
    officer: "Marketing Officer",
    post: "CEo - marketing",
    date: "THoda Department - Mar  4 , 2018 - Aug 30 ,2021",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi repudiandae quod ducimus voluptas atque unde vitae ut consequuntur delectus, perferendis quisquam ab cum dignissimos numquam beatae iste ad, distinctio amet!",
  },
  {
    id: 3,
    image: "../../img/t3.jpg",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    officer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatment. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris",
  },
  {
    id: 4,
    image: "../../img/t1.jpg",
    design: "Default name",
    name: "Davei Luace",
    officer: "Chief Operating Manager",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "When managment is so important. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 5,
    image: "../../img/t3.jpg",
    design: "Rainbow-Themes",
    name: "Nevine Acotanza",
    officer: "Chief Operating Officer",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 6,
    image: "../../img/t2.jpg",
    design: "Bound - Trolola",
    name: "Jone Duone Joe",
    officer: "Operating Officer",
    post: "Web App Development",
    date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
];

export default TestimonialAPi;
